# Generated by Django 4.2.6 on 2023-10-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
