# Generated by Django 4.2.6 on 2023-10-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
